### ISSUE TITLE
[Bug] problem building a fresh `react-static create` project

### ISSUE THREAD

**Issue by arnorhs** [react-static/react-static#1189]
### Reporting a bug?

Yes

### Environment
```
tolvi:react-static-test arnorhs$ npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers
npx: installed 1 in 2.306s

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 649.69 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 57.0.4
    Safari: 11.1.2
  npmPackages:
    react: ^16.8.2 => 16.8.6 
    react-dom: ^16.8.2 => 16.8.6 
    react-static: ^7.0.0 => 7.0.5 
    react-static-plugin-reach-router: ^7.0.0 => 7.0.0 
    react-static-plugin-sitemap: ^7.0.0 => 7.0.0 
    react-static-plugin-source-filesystem: ^7.0.0 => 7.0.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-rename: 2.2.2
    react-static: 7.0.10
```

### Steps to Reproduce the problem

npm install -g react-static
react-static create react-static-test
cd react-static-test && react-static build

### Expected Behavior

build is successful

### Observed behavior:
```
tolvi:react-static-test arnorhs$ react-static build
Bundling application for Production...

Cleaning dist...
[✓] Dist cleaned (0.8s)
Cleaning artifacts...
[✓] Artifacts cleaned
Building Routes...
Importing routes from directory...
[✓] Routes Built (0.4s)
Building Templates...
[✓] Templates Built
Copying public directory...
[✓] Public directory copied
Bundling App...
Version: webpack 4.31.0
Time: 6593ms
Built at: 2019-05-17 14:46:13
                             Asset       Size  Chunks  Chunk Names
                  main.7bac185f.js   8.62 KiB       0  main
               styles.e85fdc1f.css  361 bytes       1  styles
      templates/styles.e85fdc1f.js   82 bytes       1  styles
templates/vendors~main.28a626d4.js    223 KiB       2  vendors~main
  [0] /Users/arnorhs/projects/frontendtests/react-static-test/node_modules/react/index.js 189 bytes {2} [built]
  [2] /Users/arnorhs/projects/frontendtests/react-static-test/node_modules/@babel/runtime/helpers/interopRequireDefault.js 147 bytes {2} [built]
 [10] (webpack)/buildin/module.js 552 bytes {2} [built]
 [22] /Users/arnorhs/projects/frontendtests/react-static-test/node_modules/@babel/runtime/helpers/extends.js 427 bytes {2} [built]
 [24] /Users/arnorhs/projects/frontendtests/react-static-test/artifacts/react-static-browser-plugins.js 454 bytes {0} [built]
 [38] /Users/arnorhs/projects/frontendtests/react-static-test/node_modules/@babel/runtime/helpers/interopRequireWildcard.js 643 bytes {2} [built]
 [41] ../lib/browser/index.js 24.6 KiB {2} [built]
 [42] /Users/arnorhs/projects/frontendtests/react-static-test/artifacts/react-static-templates.js 5.62 KiB {0} [built] [failed] [1 error]
 [46] multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js 52 bytes {0} [built]
 [47] ../lib/bootstrapPlugins.js 472 bytes {2} [built]
[109] ../lib/bootstrapTemplates.js 722 bytes {2} [built]
[110] ../lib/bootstrapApp.js 1.48 KiB {2} [built]
[111] /Users/arnorhs/projects/frontendtests/react-static-test/node_modules/@babel/runtime/helpers/objectWithoutProperties.js 665 bytes {2} [built]
[113] ../lib/browser/hooks/useStaticInfo.js 624 bytes {2} [built]
[115] /Users/arnorhs/projects/frontendtests/react-static-test/src/index.js 656 bytes {0} [built]
    + 108 hidden modules

ERROR in /Users/arnorhs/projects/frontendtests/react-static-test/artifacts/react-static-templates.js
Module build failed (from ./babel-loader/lib/index.js):
TypeError: Property value expected type of string but got null
    at Object.validate (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at validate (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.StringLiteral (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/builders/generated/index.js:335:31)
    at idOption (/Users/arnorhs/projects/frontendtests/react-static-test/node_modules/babel-plugin-universal-import/index.js:134:49)
    at PluginPass.Import (/Users/arnorhs/projects/frontendtests/react-static-test/node_modules/babel-plugin-universal-import/index.js:241:13)
    at newFn (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:76:12)
    at transformFile (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ../lib/bootstrapTemplates.js 7:16-64 15:20-68
 @ multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js
Child extract-css-chunks-webpack-plugin css-loader/dist/cjs.js??ref--4-oneOf-2-1!postcss-loader/src/index.js??postcss!../../../../../../Users/arnorhs/projects/frontendtests/react-static-test/src/app.css:
    [0] ./css-loader/dist/cjs.js??ref--4-oneOf-2-1!./postcss-loader/src??postcss!/Users/arnorhs/projects/frontendtests/react-static-test/src/app.css 717 bytes {0} [built]
    [1] ./css-loader/dist/runtime/api.js 2.35 KiB {0} [built]

                => There were ERRORS during the prod build stage! :(
                => Fix them and try again!
              
Version: webpack 4.31.0
Time: 1640ms
Built at: 2019-05-17 14:46:08
        Asset      Size  Chunks  Chunk Names
static-app.js  27.1 KiB       0  main
 [0] external "react" 42 bytes {0} [built]
 [5] (webpack)/buildin/module.js 552 bytes {0} [built]
 [6] /Users/arnorhs/projects/frontendtests/react-static-test/artifacts/react-static-browser-plugins.js 516 bytes {0} [built]
 [7] external "/usr/local/lib/node_modules/react-static/lib/browser" 42 bytes {0} [built]
 [8] /Users/arnorhs/projects/frontendtests/react-static-test/artifacts/react-static-templates.js 5.62 KiB {0} [built] [failed] [1 error]
[11] multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js 52 bytes {0} [built]
[12] ../lib/bootstrapPlugins.js 472 bytes {0} [built]
[13] ../lib/bootstrapTemplates.js 722 bytes {0} [built]
[14] ../lib/bootstrapApp.js 1.48 KiB {0} [built]
[15] external "@babel/runtime/helpers/interopRequireWildcard" 42 bytes {0} [built]
[16] external "@babel/runtime/helpers/interopRequireDefault" 42 bytes {0} [built]
[17] external "@babel/runtime/helpers/extends" 42 bytes {0} [built]
[18] external "@babel/runtime/helpers/objectWithoutProperties" 42 bytes {0} [built]
[19] external "/usr/local/lib/node_modules/react-static/lib/browser/hooks/useStaticInfo" 42 bytes {0} [built]
[20] /Users/arnorhs/projects/frontendtests/react-static-test/src/index.js 746 bytes {0} [built]
    + 9 hidden modules

ERROR in /Users/arnorhs/projects/frontendtests/react-static-test/artifacts/react-static-templates.js
Module build failed (from ./babel-loader/lib/index.js):
TypeError: Property value expected type of string but got null
    at Object.validate (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/definitions/utils.js:161:13)
    at validate (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/validators/validate.js:17:9)
    at builder (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/builders/builder.js:46:27)
    at Object.StringLiteral (/usr/local/lib/node_modules/react-static/node_modules/@babel/types/lib/builders/generated/index.js:335:31)
    at idOption (/Users/arnorhs/projects/frontendtests/react-static-test/node_modules/babel-plugin-universal-import/index.js:134:49)
    at PluginPass.Import (/Users/arnorhs/projects/frontendtests/react-static-test/node_modules/babel-plugin-universal-import/index.js:241:13)
    at newFn (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/usr/local/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:76:12)
    at transformFile (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/usr/local/lib/node_modules/react-static/node_modules/@babel/core/lib/transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ../lib/bootstrapTemplates.js 7:16-64 15:20-68
 @ multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js

                => There were ERRORS during the node build stage! :(
                => Fix them and try again!
              
[✓] App Bundled (7.9s)
Fetching Site Data...
[✓] Site Data Downloaded
Fetching Route Data...
[=====================================================================================================] 104/104 100% 17333/s 0.0s
[✓] Route Data Downloaded (0.1s)
Exporting HTML across 4 threads...
  Error: Cannot find module '/Users/arnorhs/projects/frontendtests/react-static-test/artifacts/static-app.js'
  
  - module.js:547 Function.Module._resolveFilename
    module.js:547:15
  
  - module.js:474 Function.Module._load
    module.js:474:25
  
  - module.js:596 Module.require
    module.js:596:17
  
  - binHelper.js:62 Module.call
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - binHelper.js:61 Module.call [as require]
    [react-static-test]/[react-static]/src/utils/binHelper.js:61:26
  
  - module.js:11 require
    internal/module.js:11:18
  
  - exportRoutes.threaded.js:20 require
    [lib]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:271 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:271:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:334 maybeInvokeDelegate
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:334:18
  
  - runtime.js:245 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:245:32
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  

  Error: Cannot find module '/Users/arnorhs/projects/frontendtests/react-static-test/artifacts/static-app.js'
  
  - module.js:547 Function.Module._resolveFilename
    module.js:547:15
  
  - module.js:474 Function.Module._load
    module.js:474:25
  
  - module.js:596 Module.require
    module.js:596:17
  
  - binHelper.js:62 Module.call
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - binHelper.js:61 Module.call [as require]
    [react-static-test]/[react-static]/src/utils/binHelper.js:61:26
  
  - module.js:11 require
    internal/module.js:11:18
  
  - exportRoutes.threaded.js:20 require
    [lib]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:271 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:271:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:334 maybeInvokeDelegate
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:334:18
  
  - runtime.js:245 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:245:32
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  

  Error: 

  Error: Cannot find module '/Users/arnorhs/projects/frontendtests/react-static-test/artifacts/static-app.js'
  
  - module.js:547 Function.Module._resolveFilename
    module.js:547:15
  
  - module.js:474 Function.Module._load
    module.js:474:25
  
  - module.js:596 Module.require
    module.js:596:17
  
  - binHelper.js:62 Module.call
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - binHelper.js:61 Module.call [as require]
    [react-static-test]/[react-static]/src/utils/b  Error: Cannot find module '/Users/arnorhs/projects/frontendtests/react-static-test/artifacts/static-app.js'
  
  - module.js:547 Function.Module._resolveFilename
    module.js:547:15
  
  - module.js:474 Function.Module._load
    module.js:474:25
  
  - module.js:596 Module.require
    module.js:596:17
  
  - binHelper.js:62 Module.call
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - binHelper.js:61 Module.call [as require]
    [react-static-test]/[react-static]/src/utils/b  Error: 

inHelper.js:61:26
  
  - module.js:11 require
    internal/module.js:11:18
  
  - exportRoutes.threaded.js:20 require
    [lib]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:271 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:271:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:334 maybeInvokeDelegate
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:334:18
  
  - runtime.js:245 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:245:32
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  

inHelper.js:61:26
  
  - module.js:11 require
    internal/module.js:11:18
  
  - exportRoutes.threaded.js:20 require
    [lib]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:271 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:271:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:334 maybeInvokeDelegate
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:334:18
  
  - runtime.js:245 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:245:32
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
```
### additional information:

- ive tried reinstalling deps on node 10, 8, even 6, but those did not work either..
- i tried a different repo too, starting all over
- dev server works fine

**Comment by arnorhs** [comment]
Heads up on this issue.. I decided to try again, by using node 10.x when installing react-static itself.

so i uninstalled react-static, and installed again globally after switching node versions, after which building for prod worked like a charm it seems.

so when i installed react-static with node 8.11.4, created a new site, ran react-static build - it fails with the documented stack trace. (does not matter which version i install the dependencies or run the build on, 6, 8, 10 - they all fail)

but when i install react-static while running node 10, all resulting generated apps build fine.

so my conclusion is that something is broken, when using a particular npm version or node version when installing react-static

**Comment by arnorhs** [comment]
so i might give it a shot figuring out why it breaks

**Comment by sw-yx** [comment]
ouch. make sure to try yarn instead of npm as well. good luck

**Comment by jonathan-chin** [comment]
I can confirm @arnorhs problem and solution.

I initially installed react-static with node v11.x and used `create` to generate a few projects. I experienced the exact same problems.

Not only did I have to globally uninstall react-static, downgrade node to 10.x, and globally reinstall react-static, I **also** need to run `create` again. building on the previously generated projects failed in the same ways.

**Comment by cortopy** [comment]
`react-static build` gives me similar errors. Running `yarn build` will use the local script (same command though) and everything is ok. Seems to me like a dependency issue

**Comment by sw-yx** [comment]
hi everyone! thanks for your issue! there is now a call for maintainers of React Static, please weigh in here: https://github.com/nozzle/react-static/issues/1259

**Comment by M1chaelTran** [comment]
having the same issue... any updates or workaround on this?

**Comment by SleeplessByte** [comment]
@arnorhs @cortopy @M1chaelTran Do any of you per chance have `react-static` installed _globally_?

**Comment by arnorhs** [comment]
@SleeplessByte yup, i have it globally installed.

no update or workaround, except like i mentioned, removing and reinstalling both the react-static and the generated project with node 10.x

**Comment by SleeplessByte** [comment]
The minimum node is going to be increased to match LTS, so 10.16.0. If that solves the issue, then we can close this.

Thanks for confirming :heart:
