### ISSUE TITLE
[Bug] No response when Select a template

### ISSUE THREAD

**Issue by zhengsk** [react-static/react-static#1236]
###  No response when Select a template
No response when Select a template

### Environment
* Mac
* node -v  : v10.15.2
* npm -v  : 6.9.0
* react-static -v  : 7.1.0

```shell
react-static -v
7.1.0
/Users/daer/.config/yarn/global/node_modules/react-static/bin/react-static:5
init().catch(e => {
      ^

TypeError: Cannot read property 'catch' of undefined
    at Object.<anonymous> (/Users/daer/.config/yarn/global/node_modules/react-static/bin/react-static:5:7)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

![image](https://user-images.githubusercontent.com/486472/59898138-0a0e0280-9422-11e9-81d4-8d44e91d94e1.png)

**Comment by jimmy-kumar** [comment]
Same behaviour (as mentioned above) with Windows.

Tried with react-static version: 7.1.0 & 7.0.10 (with 7.0.10: No error on running react-static -v)

```
System:
  OS: Windows 7
  CPU: (4) x64 Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
  Memory: 1.27 GB / 7.67 GB
Binaries:
  Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
  npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Internet Explorer: 11.0.9600.18377
```

**Comment by is2ei** [comment]
@zhengsk @jimmy-kumar 

This issue might be fixed in this commit:
https://github.com/react-static/react-static/commit/b98ed50313845f8f05f9f5ce1abd7e9d2d9c8dc5#diff-13e5863231913cbd00a5e70ac9792890
