### ISSUE TITLE
[Bug] Site data is undefined in the 404 page

### ISSUE THREAD

**Issue by ghost** [react-static/react-static#1261]
### Reporting a bug?

  Provide as much information as you can to reproduce the issue.
  **If the issue is not reproducible, it can't be fixed!**

```
Exporting HTML...
  Error: Trace: TypeError: Failed exporting HTML for URL 404 (../src/pages/404.js): Cannot read property 'fccidData' of undefined
      at fccidData (/Volumes/X02-X/Users/xili/Developer/salary-benefit-prototype/artifacts/static-app.js:654:32)
      at c (/Volumes/X02-X/Users/xili/Developer/salary-benefit-prototype/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:501)
      at Sa (/Volumes/X02-X/Users/xili/Developer/salary-benefit-prototype/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:1)
      at a.render (/Volumes/X02-X/Users/xili/Developer/salary-benefit-prototype/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:467)
      at a.read (/Volumes/X02-X/Users/xili/Developer/salary-benefit-prototype/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
      at renderToString (/Volumes/X02-X/Users/xili/Developer/salary-benefit-prototype/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
      at renderToStringAndExtract (/usr/local/lib/node_modules/react-static/src/static/exportRoute.js:137:21)
      at renderToStringAndExtract (/usr/local/lib/node_modules/react-static/src/static/exportRoute.js:194:15)
      at tryCatch (/usr/local/lib/node_modules/react-static/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/react-static/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/react-static/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (/usr/local/lib/node_modules/react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (/usr/local/lib/node_modules/react-static/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at /usr/local/lib/node_modules/react-static/bin/react-static:6:11
```

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```

    "react-static-plugin-reach-router": "^7.0.0",
    "react-static-plugin-sitemap": "^7.0.0",
    "react-static-plugin-source-filesystem": "^7.0.0",
    "react-static": "^7.0.0",

```

of course include any other package versions here if relevant. 

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1.  Add `getSiteData` in `static.config.js` file
2.  Use the `useSiteData` inside `App.js` file
3.  Build site
4. Error

### Expected Behavior

Build the site with site data

**Comment by nddery** [comment]
I couldn't replicate this on 7.1.0.

Following the steps listed, I was able to run `yarn build` successfully and the site data I had defined was available in all routes (404 included). I couldn't load a page when running `yarn start`, as I'd get the following error:

> App suspended while rendering, but no fallback UI was specified.

You mention using `useSiteData` from within `App.js` - per the [documentation](https://github.com/react-static/react-static/blob/master/docs/api.md#usesitedata), you need to 
"wrap components using `useSiteData()` with React's `<Suspense fallback="..."></Suspense>`" - I am not seeing this in your replication steps (I don't think you'd want to wrap the whole `<App>` in a suspense component though, unclear) ?

Trying to use `useSiteData` directly in the `src/pages/404.js` (or any other pages/templates), I would successfully retrieve it while either running `yarn start` or `yarn build && serve dist`.

What does your `getSiteData` function looks like ? Can you successfully read site data from within components wrapped in `<Suspense>` ?
