### ISSUE TITLE
[Bug] Build is failing due to Babel

### ISSUE THREAD

**Issue by robiharid** [react-static/react-static#1318]
'yarn start' works
'yarn build' fails

` Error: Trace: { code: 'MODULE_NOT_FOUND' }
      at init.catch.e (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\bin\react-  static:6:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  Error: Cannot find module 'F:\OneDrive\Web Development\Development Work\TypeScript\my-static  -site\artifacts\static-app.js'

  - loader.js:636 Function.Module._resolveFilename`

even more

`
ERROR in F:/OneDrive/Web Development/Development Work/TypeScript/my-static-site/artifacts/react-static-templates.js
Module build failed (from ./babel-loader/lib/index.js):
TypeError: Property value expected type of string but got null
    at Object.validate (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\types\lib\definitions\utils.js:164:13)
    at validateField (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\types\lib\validators\validate.js:22:9)
    at validate (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\types\lib\validators\validate.js:16:3)
    at builder (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\types\lib\builders\builder.js:46:27)
    at Object.StringLiteral (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\types\lib\builders\generated\index.js:337:31)
    at idOption (F:\OneDrive\Web Development\Development Work\TypeScript\my-static-site\node_modules\babel-plugin-universal-import\index.js:134:49)
    at PluginPass.Import (F:\OneDrive\Web Development\Development Work\TypeScript\my-static-site\node_modules\babel-plugin-universal-import\index.js:241:13)
    at newFn (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\traverse\lib\visitors.js:195:21)
    at NodePath._call (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (C:\Users\robih\AppData\Roaming\npm\node_modules\react-static\node_modules\@babel\traverse\lib\path\context.js:88:12)`

i have tried removing yarn.lock, 'yarn', 'yarn upgrade', 'yarn upgrade react-static'

**Comment by robiharid** [comment]
I have also tried 
react-static build --dev and --debug which both give me errors still

**Comment by SleeplessByte** [comment]
You most likely have a bug in one of your pages. I doubt this is a `react-static` bug. 

The reason it works on `start` is that not all pages are pregenerated. Try to find out which page it breaks on, and then try going there when using `start`. You'll likely encounter the error then as well.

**Comment by robiharid** [comment]
> You most likely have a bug in one of your pages. I doubt this is a `react-static` bug.
> 
> The reason it works on `start` is that not all pages are pregenerated. Try to find out which page it breaks on, and then try going there when using `start`. You'll likely encounter the error then as well.

These are all freshly generated pages from the react-static create

Whilst it may be a bug on one of these pages, if the fault occurs out of the box it is a react-static bug.

I believe a lot of errors referenced blog post 3 which worked fine - any more ideas?

**Comment by SleeplessByte** [comment]
Same as https://github.com/react-static/react-static/issues/1307#issuecomment-532696446, I think there is a bug in the `basic` template. Is that the one you used? If that's the case, I'll try to reproduce and fix :)

**Comment by robiharid** [comment]
> Same as [#1307 (comment)](https://github.com/react-static/react-static/issues/1307#issuecomment-532696446), I think there is a bug in the `basic` template. Is that the one you used? If that's the case, I'll try to reproduce and fix :)

Thanks bud! Yes I used both basic and the typescript template (react-static-typescript-plugin), I came across your comment yesterday... 

if it helps I am on react-static v7.2.2 but the package.json says ^7.2.0 (i think the caret upgrades to latest minor version)

when i use --debug i get warnings and then a final error about babel

**Comment by robiharid** [comment]
> Same as [#1307 (comment)](https://github.com/react-static/react-static/issues/1307#issuecomment-532696446), I think there is a bug in the `basic` template. Is that the one you used? If that's the case, I'll try to reproduce and fix :)

Hey dude its been well over a month have you released a fix yet - I just want to start working on static

**Comment by lucusp** [comment]
My issue may be different but I cannot build on 7.2.3 either. There's a reference to the issue on spectrum: https://spectrum.chat/react-static/general/einval-invalid-argument-mkdir~106e4547-3e4d-47c5-831f-4e99f64184bd
