### ISSUE TITLE
[Bug] Circular JSON passed as data causes a crash

### ISSUE THREAD

**Issue by sney-js** [react-static/react-static#1320]
### Description

When you pass a circular json within `getData` of `static.config.js`, we get a circular JSON error.

### Steps to Reproduce the problem

Within `static.config.js`, `getRoutes` method, add: 
```      
     let page1 = { a: {} };
     page1["a"] = page1;
     return {
          path: "/",
          template: 'src/app/page/Page',
          getData: () => ({
                page: page1,
           }),
     }
```

This throws an error: 
```
Error: TypeError: Converting circular structure to JSON
at JSON.stringify (<anonymous>)
at stringify (<project>/node_modules/express/lib/response.js:1123:12)
at ServerResponse.json (<project>/node_modules/express/lib/response.js:260:14)
at json (<project>/node_modules/react-static/src/static/webpack/runDevServer.js:146:21)
at tryCatch (<project>/node_modules/regenerator-runtime/runtime.js:45:40)
at Generator.invoke [as _invoke] (<project>/node_modules/regenerator-runtime/runtime.js:271:22)
at Generator.prototype.(anonymous function) [as next] (<project>/node_modules/regenerator-runtime/runtime.js:97:21)
at asyncGeneratorStep (<project>/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
at _next (<project>/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

```

I am working with Contentful where pages can include other pages that have reference to current page. Unless I clean the data before I pass it to the route, is there any way to fix this issue?

**Comment by SleeplessByte** [comment]
This is not a bug, and works as intended. It needs to serialise data data in order to build the "data file". 

There is a method to fix this using a [`JSON.stringify` _replacer_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value), but we can't (and won't) implement that because it will strip data without telling you that it does, which can lead to "why isn't my data there" bug reports, and re-building the cyclic data is different for everyone.

I think the easiest solutions for you are:
- manually clean it up
- add the following code:

https://github.com/douglascrockford/JSON-js/blob/master/cycle.js

```javascript
const page = JSON.decycle(yourCyclicPageData)
```

Then on the front end, if you must, you can RE-BUILD the cyclic references:

```javascript
const { page: decycledPage } = useRouteData()
const page = JSON.recycle(decycledPage)
```

**Comment by sney-js** [comment]
Thank you @SleeplessByte . That is fair.
