### ISSUE TITLE
[Bug] Cannot read property 'catch' of undefined when running react-static --help

### ISSUE THREAD

**Issue by jzgdev** [react-static/react-static#1335]
## Environment
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 294.33 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.6.0 - ~/n/bin/node
    npm: 6.12.1 - ~/n/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 64.0
    Safari: 13.0.3

```

1.  successfully install `npm i -g react-static` on above environment
2.  run `react-static --help`
3.  Successfully see the help output but also this error: 

```
/Users/jzgdev/n/lib/node_modules/react-static/bin/react-static:5
init().catch(e => {
      ^

TypeError: Cannot read property 'catch' of undefined
    at Object.<anonymous> (/Users/jzgdev/n/lib/node_modules/react-static/bin/react-static:5:7)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)`
```

### Expected Behavior

Expected to not receive an error.

**Comment by nddery** [comment]
I think this is a duplicate of https://github.com/react-static/react-static/issues/1260 and would be fixed by https://github.com/react-static/react-static/pull/1313 - unclear if it's published or not yet.

**Comment by jzgdev** [comment]
Ahh yes, appears to be a duplicate. My fault for not searching the current issues more closely.
