### ISSUE TITLE
[To be documented] React-static fails to start if rebuildRoutes() is put into static.config.js

### ISSUE THREAD

**Issue by kanyck** [react-static/react-static#1403]
```
yarn start
yarn run v1.22.4
$ react-static start
Starting Development Server...
  Error: Routes cannot be rebuilt yet!
  
  - getRoutes.js:12 Function.current
    [rs-md]/[react-static]/src/static/getRoutes.js:12:9
  
  - getRoutes.js:8 rebuildRoutes
    [rs-md]/[react-static]/src/static/getRoutes.js:8:17
  
  - static.config.js:7 Object.<anonymous>
    /home/kanyck/sites/rs-md/static.config.js:7:1
  
  - loader.js:1158 Module._compile
    internal/modules/cjs/loader.js:1158:30
... and so on...
```
The same with chokidar:
```
yarn start
yarn run v1.22.4
$ react-static start
Starting Development Server...
Fetching Site Data...
[✓] Site Data Downloaded
/home/kanyck/sites/rs-md/node_modules/react-static/lib/static/getRoutes.js:40
  throw new Error('Routes cannot be rebuilt yet!');
  ^

Error: Routes cannot be rebuilt yet!
    at Function.current (/home/kanyck/sites/rs-md/node_modules/react-static/src/static/getRoutes.js:12:9)
    at rebuildRoutes (/home/kanyck/sites/rs-md/node_modules/react-static/src/static/getRoutes.js:8:17)
    at FSWatcher.<anonymous> (/home/kanyck/sites/rs-md/static.config.js:6:45)
    at FSWatcher.emit (events.js:311:20)
    at FSWatcher.<anonymous> (/home/kanyck/sites/rs-md/node_modules/chokidar/index.js:200:38)
    at FSWatcher._emit (/home/kanyck/sites/rs-md/node_modules/chokidar/index.js:241:5)
    at FSWatcher.NodeFsHandler._handleDir (/home/kanyck/sites/rs-md/node_modules/chokidar/lib/nodefs-handler.js:340:49)
    at FSWatcher.<anonymous> (/home/kanyck/sites/rs-md/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/kanyck/sites/rs-md/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqCallback.oncomplete (fs.js:167:5)

```
react-static v7.2.3

### Steps to Reproduce the problem

1.  enable rebuildRoutes as described in api.md
2.  run `yarn start`

**Comment by SleeplessByte** [comment]
Please post your full `static.config.js`

**Comment by kanyck** [comment]
```
import path from 'path'
import { rebuildRoutes } from 'react-static/node'
import jdown from 'jdown'
import chokidar from 'chokidar'

// chokidar.watch('content').on('all', () => rebuildRoutes())

export default {
  getSiteData: () => ({
    title: 'Capture Diem - сайт о фотографии и не только',
  }),
  getRoutes: async () => {
    const { posts, home, about } = await jdown('content')
    return [
      {
        path: '/',
        getData: () => ({
          ...home,
        }),
      },
      {
        path: '/about',
        getData: () => ({
          about,
        }),
      },
      {
        path: '/blog',
        getData: () => ({
          posts,
        }),
        children: posts.map(post => ({
          path: `/post/${post.slug}`,
          template: 'src/containers/Post',
          getData: () => ({
            post,
          }),
        })),
      },
    ]
  },
  plugins: [
    [
      require.resolve('react-static-plugin-source-filesystem'),
      {
        location: path.resolve('./src/pages'),
      },
    ],
    require.resolve('react-static-plugin-sitemap'),
    require.resolve('react-static-plugin-reach-router'),
    require.resolve('react-static-plugin-styled-components'),
  ],
}
```

**Comment by SleeplessByte** [comment]
`rebuildRoutes` is now called _before_ `getRoutes` is ever called. That won't work, unfortunately.

For now, try:

```javascript
import path from 'path'
import { rebuildRoutes } from 'react-static/node'
import jdown from 'jdown'
import chokidar from 'chokidar'

let isReady = false

chokidar.watch('content').on('all', () => isReady  && rebuildRoutes())

export default {
  getSiteData: () => ({
    title: 'Сайт о фотографии и не только',
  }),
  getRoutes: async () => {
    isReady = true

    ...
  }
}
```

**Comment by kanyck** [comment]
Yep! That works.
I think this example should get into the docs, otherwise it's quite confusing...
Closing...

**Comment by SleeplessByte** [comment]
If you have a spare 5 minutes, could you PR that?

**Comment by kanyck** [comment]
Not right now...
Would have to find out how to PR, that would demand much more than 5 min (and switching the context).
Sorry for that. I promise I'll learn how to do that as soon as I have a spare hour)))

**Comment by SleeplessByte** [comment]
Leaving this open until it's documented! :D

**Comment by kanyck** [comment]
Thanks a lot!
