### ISSUE TITLE
[Bug] Build fails: There were ERRORS during the prod build stage! :(

### ISSUE THREAD

**Issue by pedro-lb** [react-static/react-static#1408]
Hello there,

We're having some issues on our build process after upgrading to `react-static@7.2.3` (latest stable) from a project that previously used `react-static@6.36`. All breaking changes were solved and `react-static start` works perfectly well.

However, `react-static build` breaks:

```
ERROR in /Users/pedrobini/Documents/repos/react-static-test/src/app.css
Module build failed (from /Users/pedrobini/Documents/repos/react-static-test/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js):
TypeError: _this[MODULE_TYPE] is not a function
    at /Users/pedrobini/Documents/repos/react-static-test/node_modules/extract-css-chunks-webpack-plugin/dist/loader.js:142:31
    at /Users/pedrobini/Documents/repos/react-static-test/node_modules/react-static/node_modules/webpack/lib/Compiler.js:343:11
    at /Users/pedrobini/Documents/repos/react-static-test/node_modules/react-static/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/pedrobini/Documents/repos/react-static-test/node_modules/react-static/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/pedrobini/Documents/repos/react-static-test/node_modules/react-static/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/pedrobini/Documents/repos/react-static-test/node_modules/react-static/node_modules/webpack/lib/Compilation.js:1414:32
    at eval (eval at create (/Users/pedrobini/Documents/repos/react-static-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ /Users/pedrobini/Documents/repos/react-static-test/src/App.js 1:882-900
 @ /Users/pedrobini/Documents/repos/react-static-test/src/index.js
 @ ../lib/bootstrapApp.js
 @ multi babel-polyfill ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js
Child extract-css-chunks-webpack-plugin css-loader/dist/cjs.js??ref--5-oneOf-2-1!../../postcss-loader/src/index.js??postcss!../../../src/app.css:
    [0] ./css-loader/dist/cjs.js??ref--5-oneOf-2-1!/Users/pedrobini/Documents/repos/react-static-test/node_modules/postcss-loader/src??postcss!/Users/pedrobini/Documents/repos/react-static-test/src/app.css 921 KiB {0} [built]
    [1] ./css-loader/dist/runtime/api.js 2.35 KiB {0} [built]

                => There were ERRORS during the prod build stage! :(
                => Fix them and try again!
              
Version: webpack 4.43.0
Time: 13539ms
Built at: 04/22/2020 9:03:44 PM
```

Then, at the end of the build:

```
Error: Invariant failed
  
  - tiny-invariant.cjs.js:11 invariant
    [react-static-test]/[tiny-invariant]/dist/tiny-invariant.cjs.js:11:15
  
  - history.min.js:1 createBrowserHistory
    [react-static-test]/[history]/cjs/history.min.js:1:3677
  
  - static-app.js:9805 Object.<anonymous>
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:9805:72
  
  - static-app.js:36 __webpack_require__
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:36:30
  
  - static-app.js:18677 Module.<anonymous>
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:18677:62
  
  - static-app.js:18702 Module.<anonymous>
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:18702:30
  
  - static-app.js:36 __webpack_require__
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:36:30
  
  - static-app.js:18635 Object.<anonymous>
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:18635:11
  
  - static-app.js:36 __webpack_require__
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:36:30
  
  - static-app.js:18109 Object.<anonymous>
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:18109:18
  
  - static-app.js:36 __webpack_require__
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:36:30
  
  - static-app.js:113 
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:113:18
  
  - static-app.js:116 
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:116:10
  
  - static-app.js:3 webpackUniversalModuleDefinition
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:3:20
  
  - static-app.js:10 Object.<anonymous>
    /Users/pedrobini/Documents/repos/react-static-test/artifacts/static-app.js:10:3
  
  - loader.js:956 Module._compile
    internal/modules/cjs/loader.js:956:30
  
  - index.js:99 Module._compile
    [react-static-test]/[pirates]/lib/index.js:99:24
  
  - loader.js:973 Module._extensions..js
    internal/modules/cjs/loader.js:973:10
  
  - index.js:104 Object.newLoader [as .js]
    [react-static-test]/[pirates]/lib/index.js:104:7
  
  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32
  
  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14
  
  - loader.js:849 Module.call
    internal/modules/cjs/loader.js:849:19
  
  - binHelper.js:62 Module.require
    [react-static-test]/[react-static]/src/utils/binHelper.js:62:26
  
  - helpers.js:74 require
    internal/modules/cjs/helpers.js:74:18
  
  - exportRoutes.threaded.js:20 _callee2$
    [react-static-test]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [react-static-test]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:274 Generator.invoke [as _invoke]
    [react-static-test]/[regenerator-runtime]/runtime.js:274:22
  
  - runtime.js:97 Generator.prototype.<computed> [as next]
    [react-static-test]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [react-static-test]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:337 maybeInvokeDelegate
    [react-static-test]/[regenerator-runtime]/runtime.js:337:18
  
  - runtime.js:248 Generator.invoke [as _invoke]
    [react-static-test]/[regenerator-runtime]/runtime.js:248:32
  
  - runtime.js:97 Generator.prototype.<computed> [as next]
    [react-static-test]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [react-static-test]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [react-static-test]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
```

### Environment

Run and copy the result of:

`npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers` 

here:

```
pedrobini@Pedros-MacBook-Pro null-leasing-pages % npx envinfo --system --npmPackages react* --binaries --npmGlobalPackages react* --browsers
npx: installed 1 in 1.373s

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.36 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 74.0
    Safari: 13.0.4
  npmPackages:
    react: ^16.8.2 => 16.13.1 
    react-apollo: ^3.1.5 => 3.1.5 
    react-dom: ^16.8.2 => 16.13.1 
    react-hot-loader: ^4.7.1 => 4.12.20 
    react-image-gallery: ^0.8.12 => 0.8.18 
    react-loading: ^2.0.3 => 2.0.3 
    react-markdown: ^4.0.3 => 4.3.1 
    react-redux: ^5.1.0 => 5.1.2 
    react-responsive-modal: ^3.5.1 => 3.6.0 
    react-router-dom: ^4.3.1 => 4.3.1 
    react-select: ^2.0.0 => 2.4.4 
    react-static: ^7.2.3 => 7.2.3 
    react-static-plugin-react-router: ^6.3.4 => 6.3.4 
    react-static-plugin-sitemap: ^7.2.3 => 7.2.3 
  npmGlobalPackages:
    react-native-surrender: 2.0.0
    react-static: 7.2.3
```

Packages:

```
"react-static": "^7.2.3",
 "react-static-plugin-sitemap": "^7.2.3",
```

### Expected Behavior

Build normally

**Comment by pedro-lb** [comment]
Related issues:


https://github.com/react-static/react-static/issues/1189


https://www.gitmemory.com/issue/react-static/react-static/1318/535010907


https://www.gitmemory.com/issue/react-static/react-static/1307/529832780

**Comment by TimMcCauley** [comment]
Hi pedro-lb - can you share your code?

**Comment by pedro-lb** [comment]
Unfortunately I can not, since it's proprietary code.

I have tried to replicate the error in a new project, but wasn't successful. The error only happens in our project.

Things we've tried:
- Removing `node_modules` & re-installing deps
- Downgrading `nodejs` to `10.16.0`

**Comment by pedro-lb** [comment]
Solved the issue.

The error was:

```
Error: Invariant failed
  
  - tiny-invariant.cjs.js:11 invariant
    [react-static-test]/[tiny-invariant]/dist/tiny-invariant.cjs.js:11:15
  
  - history.min.js:1 createBrowserHistory
    [react-static-test]/[history]/cjs/history.min.js:1:3677
```

We were only getting `Error: Invariant failed` as an error message since we were using `history` as a dependency, while still injecting a `<Router />` component from `react-router-dom`.

By removing `history` and using `BrowserRouter` the error gets more detailed:

```
Error: Failed exporting HTML for URL partner-werden (/Users/pedrobini/Documents/repos/react-static-test/src/fullpages/Partner): Invariant failed
  - tiny-invariant.cjs.js:11 invariant
    [react-static-test]/[tiny-invariant]/dist/tiny-invariant.cjs.js:11:15
  - history.min.js:1 createBrowserHistory
    [react-static-test]/[history]/cjs/history.min.js:1:3677
  - BrowserRouter.js:46 new BrowserRouter
    [react-static-test]/[react-router-dom]/BrowserRouter.js:46:197
```

With the new error we were able to find more information, such as [this issue](https://stackoverflow.com/questions/55202110/error-failed-exporting-html-for-url-about-src-pages-about-js-invariant-faile).

Removing the `<Router />` component solves the issue since `react-static-plugin-react-router` already wraps the content into a router ready for react-static goodness.

Note: due to the upgrade, we also had to update some dependencies:

- `extract-css-chunks-webpack-plugin`
- `react-static-plugin-react-router`

Thanks @TimMcCauley.
