### ISSUE TITLE
Basic template app crashed on URI malformed error

### ISSUE THREAD

**Issue by bentranmyriota** [react-static/react-static#1454]
### Reporting a bug?
Hi, I encountered the below issue while testing the basic template with URL input `http://localhost:3000/?query=%%uri_malformed%%`
```
An internal error occured!

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at RoutesInner (http://localhost:3000/main.js:68271:17)
    at renderWithHooks (http://localhost:3000/main.js:35496:22)
    at mountIndeterminateComponent (http://localhost:3000/main.js:38108:17)
    at beginWork (http://localhost:3000/main.js:39188:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/main.js:20888:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/main.js:20937:20)
    at invokeGuardedCallback (http://localhost:3000/main.js:20990:35)
    at beginWork$1 (http://localhost:3000/main.js:43754:11)
    at performUnitOfWork (http://localhost:3000/main.js:42718:16)
          
```

### Environment

```


  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 6.19 GB / 15.11 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.3.0 - /usr/bin/node
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 77.0.1
  npmPackages:
    react: ^16.9.0 => 16.13.1 
    react-dom: ^16.9.0 => 16.13.1 
    react-static: ^7.2.0 => 7.4.0 
    react-static-plugin-reach-router: ^7.2.0 => 7.4.0 
    react-static-plugin-sitemap: ^7.2.0 => 7.4.0 
    react-static-plugin-source-filesystem: ^7.2.0 => 7.4.0 
```

### Steps to Reproduce the problem
1.  Run `react-static create basic`
2.  Open chrome browser and enter `http://localhost:3000/?query=%%uri_malformed%%`

### Expected Behavior
Would not crash and redirect to the root/default route?

**Comment by SleeplessByte** [comment]
Personally, I don't think we should fix this, because malformed URIs will result in malformed / unpredicatable application state, BUT, we'll take a PR that captures the issue. 

You only need to try/catch in `RoutesInner`.

**Comment by bentranmyriota** [comment]
try/catch in `RoutesInner` sounds good enough. However, i don't think it can be done via configuration or plugins. I couldn't find an example in the docs

**Comment by SleeplessByte** [comment]
Yeh, we would need to change the core code (`packages/react-static`)
