### ISSUE TITLE
[Bug] `ReactDOMServer does not yet support Suspense.` errors everywhere...

### ISSUE THREAD

**Issue by AJTJ** [react-static/react-static#1501]
### Reporting a bug?

Unable to build my project. 

I'm exporting on 4 threads and all 4 of them are failing with this type of error:
```
Exporting HTML across 4 threads...
  Error: Failed exporting HTML for URL ylc_website (__react_static_root__/src/Home): Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for   the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  
  - react-dom-server.node.production.min.js:44 a.b.read
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:107
  
  - react-dom-server.node.production.min.js:54 renderToString
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364
  
  - exportRoute.js:167 renderToStringAndExtract
    [static-ylc]/[react-static]/src/static/exportRoute.js:167:21
  
  - exportRoute.js:224 _callee$
    [static-ylc]/[react-static]/src/static/exportRoute.js:224:15
  
  - runtime.js:45 tryCatch
    [static-ylc]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:274 Generator.invoke [as _invoke]
    [static-ylc]/[regenerator-runtime]/runtime.js:274:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [static-ylc]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [static-ylc]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [static-ylc]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```
which is to say that I'm getting `ReactDOMServer does not yet support Suspense.` errors

I've checked and it seems like some people have had similar error messages come up with react-static, but I can't seem to find the solution.

in #1357 @SleeplessByte quotes this note:
> Note: Make sure to wrap components using `useSiteData()` with React's `<Suspense fallback="..."></Suspense>`. More information on the subject is available here.

My `Nav` component is using `useSiteData()` but even with commenting out that import I'm still getting this error.

One theory I have is that _perhaps_ this has to do with writing "node-safe" code, so I went through and checked any references to `window` or `document` to write type-checks for their existence, but this was to no avail.

The repo can be found here: https://github.com/Yukon-Literacy-Coalition/ylc_website
You can `yarn start` or `yarn build`, the build would be where these issues arise

### Environment

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Memory: 168.91 MB / 8.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 76.0.1
    Firefox Developer Edition: 65.0
    Safari: 13.1.2
  npmPackages:
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1
    react-elastic-carousel: ^0.6.6 => 0.6.6
    react-markdown: ^4.3.1 => 4.3.1
    react-moment: ^0.9.7 => 0.9.7
    react-multi-carousel: ^2.5.5 => 2.5.5
    react-router: ^5.2.0 => 5.2.0
    react-router-dom: ^5.2.0 => 5.2.0
    react-scroll: ^1.7.16 => 1.7.16
    react-static: ^7.2.0 => 7.4.0
    react-static-plugin-emotion: ^7.2.2 => 7.2.2
    react-static-plugin-favicons: ^2.0.0 => 2.0.0
    react-static-plugin-reach-router: ^7.2.0 => 7.4.0
    react-static-plugin-react-router: ^7.4.0 => 7.4.0
    react-static-plugin-sitemap: ^7.2.0 => 7.4.0
    react-static-plugin-source-filesystem: ^7.2.0 => 7.4.0
    react-static-plugin-styled-components: ^7.3.0 => 7.3.0
    react-text-loop: ^2.3.0 => 2.3.0
  npmGlobalPackages:
    react-static: 7.4.0

```

### Steps to Reproduce the problem

The parent repo is here: https://github.com/Yukon-Literacy-Coalition/ylc_website
You can `yarn start` or `yarn build`, the build would be where these issues arise

**Comment by AJTJ** [comment]
More information I can offer is that when I attempt to run `react-static build --staging` I get several of these errors:

```
ERROR in /Users/aaronjanke/web_projects/static-ylc/artifacts/react-static-templates.js
Module build failed (from ./babel-loader/lib/index.js):
TypeError: /Users/aaronjanke/web_projects/static-ylc/artifacts/react-static-templates.js: Property value expected type of string but got null
    at Object.validate (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/types/lib/definitions/utils.js:160:13)
    at validateField (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.StringLiteral (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/types/lib/builders/generated/index.js:350:31)
    at idOption (/Users/aaronjanke/web_projects/static-ylc/node_modules/babel-plugin-universal-import/index.js:134:49)
    at PluginPass.Import (/Users/aaronjanke/web_projects/static-ylc/node_modules/babel-plugin-universal-import/index.js:241:13)
    at newFn (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/traverse/lib/index.js:66:12)
    at transformFile (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:107:29)
    at transformFile.next (<anonymous>)
    at run (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/core/lib/transformation/index.js:35:12)
    at run.next (<anonymous>)
    at Function.transform (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/@babel/core/lib/transform.js:27:41)
    at transform.next (<anonymous>)
    at step (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/gensync/index.js:254:32)
    at gen.next (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/gensync/index.js:266:13)
    at async.call.value (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-static/node_modules/gensync/index.js:216:11)
 @ ../lib/bootstrapTemplates.js 7:16-64
 @ multi ../lib/bootstrapPlugins.js ../lib/bootstrapTemplates.js ../lib/bootstrapApp.js
```

and then these:
```
Exporting HTML across 4 threads...
  Error: Cannot find module '/Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js'
  
  - loader.js:581 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:581:15
  
  - loader.js:507 Function.Module._load
    internal/modules/cjs/loader.js:507:25
  
  - loader.js:637 Module.call
    internal/modules/cjs/loader.js:637:17
  
  - binHelper.js:62 Module.require
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - exportRoutes.threaded.js:20 _callee2$
    [lib]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:274 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:274:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:337 maybeInvokeDelegate
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:337:18
  
  - runtime.js:248 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:248:32
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
```

**Comment by SleeplessByte** [comment]
My guess is that [_this `Suspense`_](https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/0902b4fcb6ce628e04050f138c7cd98663b5da6e/src/App.jsx#L66) is not [_our `Suspense`_](https://github.com/react-static/react-static/blob/master/packages/react-static/src/bootstrapApp.js#L18). It should be, so I don't know why this is happening.

**Comment by AJTJ** [comment]
@SleeplessByte I'm trying to follow common practices, for the most part, and I don't think the way I've set up my `App.jsx` is very "off the beaten path". I'm wondering if something else could cause this error. I could have missed something... I'd really like to figure this out, so if there's something you recommend digging into, I appreciate all kinds of direction.

**Comment by AJTJ** [comment]
running `react-static build --staging --debug` throws `window is not defined` errors. Which is surprising, since I'm only getting the `Suspense` errors when I try to simply build.

Several like this:
```
ReferenceError: window is not defined
  
  - universalModuleDefinition:10 Object.<anonymous>
    [static-ylc]/[netlify-cms-app]/dist/webpack:/NetlifyCmsApp/webpack/universalModuleDefinition:10:4
  
  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30
  
  - index.js:99 Module._compile
    [lib]/[react-static]/[pirates]/lib/index.js:99:24
  
  - loader.js:700 Module._extensions..js
    internal/modules/cjs/loader.js:700:10
  
  - index.js:104 Object.newLoader [as .js]
    [lib]/[react-static]/[pirates]/lib/index.js:104:7
  
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
  
  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12
  
  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3
  
  - loader.js:637 Module.call
    internal/modules/cjs/loader.js:637:17
  
  - binHelper.js:62 Module.require
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - static-app.js:1063 Object.<anonymous>
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:1063:18
  
  - static-app.js:30 __webpack_require__
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:30:30
  
  - static-app.js:7031 Module.<anonymous>
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:7031:73
  
  - static-app.js:30 __webpack_require__
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:30:30
  
  - static-app.js:6864 Module.<anonymous>
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:6864:36
  
  - static-app.js:30 __webpack_require__
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:30:30
  
  - static-app.js:6804 Object.<anonymous>
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:6804:17
  
  - static-app.js:30 __webpack_require__
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:30:30
  
  - static-app.js:6654 Object.<anonymous>
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:6654:1
  
  - static-app.js:30 __webpack_require__
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:30:30
  
  - static-app.js:94 
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:94:18
  
  - static-app.js:97 
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:97:10
  
  - static-app.js:3 webpackUniversalModuleDefinition
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:3:20
  
  - static-app.js:10 Object.<anonymous>
    /Users/aaronjanke/web_projects/static-ylc/artifacts/static-app.js:10:3
  
  - loader.js:689 Module._compile
    internal/modules/cjs/loader.js:689:30
  
  - index.js:99 Module._compile
    [lib]/[react-static]/[pirates]/lib/index.js:99:24
  
  - loader.js:700 Module._extensions..js
    internal/modules/cjs/loader.js:700:10
  
  - index.js:104 Object.newLoader [as .js]
    [lib]/[react-static]/[pirates]/lib/index.js:104:7
  
  - loader.js:599 Module.load
    internal/modules/cjs/loader.js:599:32
  
  - loader.js:538 tryModuleLoad
    internal/modules/cjs/loader.js:538:12
  
  - loader.js:530 Function.Module._load
    internal/modules/cjs/loader.js:530:3
  
  - loader.js:637 Module.call
    internal/modules/cjs/loader.js:637:17
  
  - binHelper.js:62 Module.require
    [lib]/[react-static]/src/utils/binHelper.js:62:26
  
  - helpers.js:22 require
    internal/modules/cjs/helpers.js:22:18
  
  - exportRoutes.threaded.js:20 _callee2$
    [lib]/[react-static]/src/static/exportRoutes.threaded.js:20:18
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:274 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:274:22
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - runtime.js:45 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:45:40
  
  - runtime.js:337 maybeInvokeDelegate
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:337:18
  
  - runtime.js:248 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:248:32
  
  - runtime.js:97 Generator.prototype.(anonymous function) [as next]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:97:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  
```

**Comment by SleeplessByte** [comment]
Would could be happening is that the `Suspense` error is a red herring and that the code actually fails on this `window`, but it bubbles up as a `Suspense` error :/

**Comment by AJTJ** [comment]
I thought if I set my CMS as a dynamic route in my `App.jsx` and remove it from `static.config.js` this might help remove these errors:
```
  ReferenceError: window is not defined
  
  - universalModuleDefinition:10 Object.<anonymous>
    [static-ylc]/[netlify-cms-app]/dist/webpack:/NetlifyCmsApp/webpack/universalModuleDefinition:10:4
```
because for whatever reason it is referencing something to do with `NetlifyCmsApp` in the stack trace.

But... I still get these errors.

Here it is with the new dynamic route
```
const App = () => (
  <Root>
    <ScrollToTop />
    <Global />
    <ThemeProvider theme={theme}>
      <PageContent className="page-content">
        <React.Suspense fallback={<Loader />}>
          <Switch>
            <Route path="/admin/">
              <CMS />
            </Route>
            <Route>
              <Routes
                render={({ routePath, getComponentForPath }) => {
                  const el = getComponentForPath(routePath);
                  // if (routePath === "ylc_website/admin") {
                  //   return <FullPage>{el}</FullPage>;
                  // } else {
                  return (
                    <FullPage routePath={routePath}>
                      <div css={appBodyStyles}>
                        <Navigation isHome={routePath === "/"} />
                        <ComponentContent routePath={routePath}>
                          {el}
                        </ComponentContent>
                        <Footer />
                      </div>
                    </FullPage>
                  );
                  // }
                }}
              />
            </Route>
          </Switch>
        </React.Suspense>
      </PageContent>
    </ThemeProvider>
  </Root>
);
```
this is challenging.

**Comment by SleeplessByte** [comment]
I won't try to remove the CMS completely from the static site. Your CMS most likely doesn't work statically at all.

**Comment by AJTJ** [comment]
@SleeplessByte so, yea I got the CMS to be a dynamic route, I think.

Extensive use of the `react-static build --staging --debug` command and solving the bugs as they come up has been useful and brought me to this error:

```
Error: Failed exporting HTML for URL ylc_website (__react_static_root__/src/Home): Invariant failed: You should not use <Switch  > outside a <Router>
...
```

I don't know why I would be getting this error when my understanding is that `Root` should be importing its own `Router`. I tried bringing the `React.Suspense` above the Root (amongst other things), but I'm still getting the error.

Here is how my App is structured
You can see it here: https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/master/src/App.jsx

```
const App = () => (
  <React.Suspense fallback={<Loader />}>
    <Root>
      <ScrollToTop />
      <Global />
      <ThemeProvider theme={theme}>
        <PageContent className="page-content">
          <Switch>
            {CMS && (
              <Route path="/admin/">
                <CMS />
              </Route>
            )}
            <Route>
              <Routes
                render={({ routePath, getComponentForPath }) => {
                  console.log({ routePath });
                  const el = getComponentForPath(routePath);
                  return (
                    <FullPage routePath={routePath}>
                      <div css={appBodyStyles}>
                        <Navigation
                          isHome={routePath === githubBasePath + "/"}
                        />
                        <ComponentContent routePath={routePath}>
                          {el}
                        </ComponentContent>
                        <Footer />
                      </div>
                    </FullPage>
                  );
                  // }
                }}
              />
            </Route>
          </Switch>
        </PageContent>
      </ThemeProvider>
    </Root>
  </React.Suspense>
);
```

**Comment by SleeplessByte** [comment]
- `react-router` _does_ do this, as shown [here](https://github.com/react-static/react-static/blob/master/packages/react-static-plugin-react-router/src/browser.api.js#L28-L30)
- `reach-router` _does_ do this as well, as shown [here](https://github.com/react-static/react-static/blob/master/packages/react-static-plugin-reach-router/src/browser.api.js#L19-L21)

However, the don't both pass down the router context on the same way (has nothing to do with react-static). So in one of our sites, I use the following code to alleviate that:

```tsx

function App(): JSX.Element {
  return (
    <ThemeProvider theme={theme}>
      <CSSReset />

      <Root>
        <Head
          defaultTitle="My Site - My Great Site"
          titleTemplate="My Site - %s"
        >
          <html lang="en" />
          <meta name="description" content="" />
          <meta name="keywords" content="" />

          <script id="google-tag-manager">{`
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-XXX');
          `}</script>
        </Head>

        <noscript>
          <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXX"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}>
          </iframe>
        </noscript>

        <Suspense fallback={<Skeleton />}>
          <Router>
            <Routes default render={renderRoute} />
          </Router>
        </Suspense>
      </Root>
    </ThemeProvider>
  )
}
```

As you can see, the structure is:

```tsx
<Root>
  <Suspense>
    <Router>
      <Routes default render={renderRoute} />
    </Router>
  </Suspense>
</Root>
```

So yes, `react-static` brings in a router, but the library you're using most likely doesn't make that router _magically_ available to its subtree.

`renderRouter`, by the way, is written like this, and allows `Wrapper` to know which route we're at (think: navigation etc):

```tsx
function renderRoute({ routePath, getComponentForPath }: RenderRouteProps): React.ReactNode {
  const routeContent= getComponentForPath(routePath)
  return (
    <Wrapper currentPath={routePath}>{routeContent}</Wrapper>
  )
}
```

**Comment by AJTJ** [comment]
@SleeplessByte 

Thanks for your reply, so the `Router` you're using here:

```
        <Suspense fallback={<Skeleton />}>
          <Router>
            <Routes default render={renderRoute} />
          </Router>
        </Suspense>
```
is just an imported router from React-Router? As in
`import { Router } from "react-router-dom";`

**Comment by SleeplessByte** [comment]
I'm using @reach/router, which has a single Router export.

If you're using react-router, you'll need to basically set it up as a nested router; I don't know if that means memory router or browser router + server router (depending on document being undefined). Thats something you'll have to try.

**Comment by AJTJ** [comment]
@SleeplessByte thanks so much your responses. So I refactored to use `@reach/router` since that seems to be what people are using with `react-static` and `react-router` seemed to have too much complexity to get working. Either way, when I run `react-static build --staging --debug` I get these errors (I was getting them earlier as well):
```
  TypeError: Failed exporting HTML for URL 404 (__react_static_root__/src/404): Cannot convert un  defined or null to object
  
  - Function.keys
  
  - Routes.js:72 
    [static-ylc]/[react-static]/src/browser/components/Routes.js:72:14
  
  - react-dom-server.node.development.js:1194 useReducer
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:1194:57
  
  - react-dom-server.node.development.js:1132 Object.useState
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:1132:10
  
  - react.development.js:1497 useState
    [static-ylc]/[react]/cjs/react.development.js:1497:21
  
  - Routes.js:61 RoutesInner
    [static-ylc]/[react-static]/src/browser/components/Routes.js:61:3
  
  - react-dom-server.node.development.js:3043 processChild
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:3043:14
  
  - react-dom-server.node.development.js:2960 resolve
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:2960:5
  
  - react-dom-server.node.development.js:3435 ReactDOMServerRenderer.render
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:3435:22
  
  - react-dom-server.node.development.js:3373 ReactDOMServerRenderer.read
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:3373:29
  
  - react-dom-server.node.development.js:3988 renderToString
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:3988:27
  
  - exportRoute.js:167 renderToStringAndExtract
    [lib]/[react-static]/src/static/exportRoute.js:167:21
  
  - exportRoute.js:224 _callee$
    [lib]/[react-static]/src/static/exportRoute.js:224:15
  
  - runtime.js:63 tryCatch
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:63:40
  
  - runtime.js:293 Generator.invoke [as _invoke]
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:293:22
  
  - runtime.js:118 Generator.next
    [lib]/[react-static]/[regenerator-runtime]/runtime.js:118:21
  
  - asyncToGenerator.js:3 asyncGeneratorStep
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:3:24
  
  - asyncToGenerator.js:25 _next
    [lib]/[react-static]/[@babel]/runtime/helpers/asyncToGenerator.js:25:9
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  

  TypeError: Failed exporting HTML for URL ylc_website (__react_static_root__/src/Home): Cannot c  onvert undefined or null to object
  
  - Function.keys
  
  - Routes.js:72 
    [static-ylc]/[react-static]/src/browser/components/Routes.js:72:14
  
  - react-dom-server.node.development.js:1194 useReducer
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:1194:57
  
  - react-dom-server.node.development.js:1132 Object.useState
    [static-ylc]/[react-dom]/cjs/react-dom-server.node.development.js:1132:10
  
  - react.development.js:1497 useState  Error: Trace: {}
      at init.catch.e (/Users/aaronjanke/.nvm/versions/node/v10.15.1/lib/node_modules/react-stati  c/bin/react-static:6:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
...
```
Any idea what this error references?

here's my App.jsx: https://github.com/Yukon-Literacy-Coalition/ylc_website/blob/master/src/App.jsx

**Comment by AJTJ** [comment]
here's the full report, if there is indeed a bug: https://gist.github.com/AJTJ/ebb35ffb1cf9de8657de9e39fc8c4f6b

**Comment by AJTJ** [comment]
I will create a new bug report for this, since this thread has gotten rather convoluted

**Comment by AJTJ** [comment]
#1503
