### ISSUE TITLE
[Docs] how to structure plugin repo

### ISSUE THREAD

**Issue by henryhoo** [react-static/react-static#1510]
I am trying to develop an existing plugin [react-static-plugin-md-pages](https://github.com/kitten/react-static-plugin-md-pages).

Look like the repo is structed in a different way --- node.api.js is under /src folder in its repo. 

When I tried to clone this plugin into my local plugins folder under project root: `/plugins/react-static-plugin-md-pages`, the plugin can not be correctly resolved by react-static

```
jxh@jxh-mbp unravel % react-static start -d
Starting Development Server...
  Error: The following error occurred in the plugin: "react-static-plugin-md-pages"

  Error: Trace: Error: Could not find a valid node.api.js or browser.api.js plugin file in "/Users/jxh/Documents/jiaxi/unravel/plugins/react-static-plugin-md-pages".
  The original location: "react-static-plugin-md-pages".
  The root location: "/Users/jxh/Documents/jiaxi/unravel".
      at map (/Users/jxh/.config/yarn/global/node_modules/react-static/src/static/getConfig.js:317:15)
      at Array.map (<anonymous>)
      at buildConfig (/Users/jxh/.config/yarn/global/node_modules/react-static/src/static/getConfig.js:350:29)
      at buildConfigFromPath (/Users/jxh/.config/yarn/global/node_modules/react-static/src/static/getConfig.js:74:10)
      at getConfig (/Users/jxh/.config/yarn/global/node_modules/react-static/src/static/getConfig.js:53:11)
      at _callee3$ (/Users/jxh/.config/yarn/global/node_modules/react-static/src/commands/start.js:25:3)
      at tryCatch (/Users/jxh/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/Users/jxh/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (/Users/jxh/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (/Users/jxh/.config/yarn/global/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (/Users/jxh/.config/yarn/global/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at /Users/jxh/.config/yarn/global/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
      at new Promise (<anonymous>)
      at Object.<anonymous> (/Users/jxh/.config/yarn/global/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
      at Object.start [as default] (/Users/jxh/.config/yarn/global/node_modules/react-static/lib/commands/start.js:145:19)
      at start (/Users/jxh/.config/yarn/global/node_modules/react-static/bin/react-static:132:50)
      at init (/Users/jxh/.config/yarn/global/node_modules/react-static/bin/react-static:46:12)
      at Object.<anonymous> (/Users/jxh/.config/yarn/global/node_modules/react-static/bin/react-static:5:1)
      at Module._compile (internal/modules/cjs/loader.js:1076:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
      at Module.load (internal/modules/cjs/loader.js:941:32)
      at Function.Module._load (internal/modules/cjs/loader.js:782:14)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
      at internal/main/run_main_module.js:17:47
      at /Users/jxh/.config/yarn/global/node_modules/react-static/bin/react-static:6:11
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Wondering what is the best way to handle such situation, I don't want to copy paste files over and over again :)

**Comment by SleeplessByte** [comment]
`/src` are the "source" files, which are built to the correct location "on build" -- you shouldn't be copying anything manually.

Is your question: **how to set up the project so I can develop a plugin**?

The easiest is to create a new plugin folder in your own react-static project, with `node.api.js` and/or `browser.api.js`, and write in there directly. Then, when you're happy, you can copy them to the `react-static-plugin-md-pages` source directory 🔢

**Comment by henryhoo** [comment]
I think the issue is react-static by default only look for `node.api.js` under folder root. For the plugin I was working with, that file is under `src` folder which is a requirement for npm pkgs. So when I try to develop that plugin (git clone the repo and move it under `plugins` folder), I need to manually copy `node.api.js` out of `src` folder

**Comment by SleeplessByte** [comment]
The `src` folder is not a requirement for non packages.

You can check out the built-in plugins inside our monorepo to see how those are built for npm (they all have a package.json with build scripts).

**Comment by SleeplessByte** [comment]
We're those clear enough
