### ISSUE TITLE
doesnt work with emotion anymore

### ISSUE THREAD

**Issue by bradennapier** [react-static/react-static#1534]
```
Starting Development Server...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
  Error: The following error occurred in the plugin: "react-static-plugin-emotion"

  Error: Trace: Error: The `emotion` package has been renamed to `@emotion/css`. Please import it like this `import { css } from '@emot  ion/css'`.
11:09:28 PM:       at Object.<anonymous> (/opt/build/repo/node_modules/emotion/dist/emotion.c  js.prod.js:3:7)
11:09:28 PM:       at Module._compile (internal/modules/cjs/loader.js:1138:30)
11:09:28 PM:       at Module._compile (/opt/build/repo/node_modules/pirates/lib/index.js:99:2  4)
11:09:28 PM:       at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
11:09:28 PM:       at Object.newLoader [as .js] (/opt/build/repo/node_modules/pirates/lib/ind  ex.js:104:7)
11:09:28 PM:       at Module.load (internal/modules/cjs/loader.js:986:32)
11:09:28 PM:       at Function.Module._load (internal/modules/cjs/loader.js:879:14)
11:09:28 PM:       at Module.call (internal/modules/cjs/loader.js:1026:19)
11:09:28 PM:       at Module.require (/opt/build/repo/node_modules/react-static/src/utils/bin  Helper.js:62:26)
11:09:28 PM:       at require (internal/modules/cjs/helpers.js:72:18)
11:09:28 PM:       at Object.<anonymous> (/opt/build/repo/node_modules/emotion/dist/emotion.c  js.js:4:20)
11:09:28 PM:       at Module._compile (internal/modules/cjs/loader.js:1138:30)
11:09:28 PM:       at Module._compile (/opt/build/repo/node_modules/pirates/lib/index.js:99:2  4)
11:09:28 PM:       at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
11:09:28 PM:       at Object.newLoader [as .js] (/opt/build/repo/node_modules/pirates/lib/ind  ex.js:104:7)
11:09:28 PM:       at Module.load (internal/modules/cjs/loader.js:986:32)
11:09:28 PM:       at Function.Module._load (internal/modules/cjs/loader.js:879:14)
11:09:28 PM:       at Module.call (internal/modules/cjs/loader.js:1026:19)
11:09:28 PM:       at Module.require (/opt/build/repo/node_modules/react-static/src/utils/bin  Helper.js:62:26)
11:09:28 PM:       at require (internal/modules/cjs/helpers.js:72:18)
```

When trying to use the latest versions of emotion with the latest plugin for emotion

**Comment by SleeplessByte** [comment]
It works with [these versions](https://github.com/react-static/react-static/blob/master/packages/react-static-plugin-emotion/package.json#L17-L19) of `emotion`.
