### ISSUE TITLE
[Bug] assetsPath and path.assets break tempate loading

### ISSUE THREAD

**Issue by codejunkienick** [react-static/react-static#1568]
### Reporting a bug?

When adding `assetsPath: 'assets'` and `paths: { assets: 'assets' }` to basic template it breaks page with message
`An error occurred loading this page's template. More information is available in the console.`

console.logs contain this error

```
main.7d6f7928.js:1 ChunkLoadError: Loading chunk 4 failed.
(error: http://localhost:3001/templates/__react_static_root__/src/pages/index.62bb425b.js)
    at Function.c.e (http://localhost:3001/assets/main.7d6f7928.js:1:1197)
    at load (http://localhost:3001/assets/main.7d6f7928.js:1:4402)
    at http://localhost:3001/assets/templates/vendors~main.8117e77c.js:1:121425
    at new Promise (<anonymous>)
    at requireAsync (http://localhost:3001/assets/templates/vendors~main.8117e77c.js:1:121123)
    at n.value (http://localhost:3001/assets/templates/vendors~main.8117e77c.js:1:7511)
    at n.value (http://localhost:3001/assets/templates/vendors~main.8117e77c.js:1:8631)
    at new n (http://localhost:3001/assets/templates/vendors~main.8117e77c.js:1:7339)
    at wi (http://localhost:3001/assets/templates/vendors~main.8117e77c.js:1:177755)```

Actual path to template is `http://localhost:3001/assets/templates/__react_static_root__/src/pages/index.62bb425b.js`

### Environment

```
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 9.98 GB / 31.33 GB
    Container: Yes
    Shell: 3.1.2 - /usr/bin/fish
  Binaries:
    Node: 15.8.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Firefox: 85.0.1
  npmPackages:
    react: ^16.9.0 => 16.14.0 
    react-dom: ^16.9.0 => 16.14.0 
    react-hot-loader: ^4.13.0 => 4.13.0 
    react-static: 7.4.2 => 7.4.2 
    react-static-plugin-reach-router: 7.4.2 => 7.4.2 
    react-static-plugin-sitemap: 7.4.2 => 7.4.2 
    react-static-plugin-source-filesystem: 7.4.2 => 7.4.2 

```
### Steps to Reproduce the problem


1. create basic template
2. add this to static.config.js
```  paths: {
    assets: "assets",
  },
  assetsPath: "assets",
```
3. yarn run build
4. yarn run serve

### Expected Behavior

template are loaded with assetsPath taken into account

### Reproducible Demo

https://github.com/codejunkienick/react-static-asset-path-bug
1. yarn run build
2. yarn run serve

**Comment by SleeplessByte** [comment]
The PR that fixes this has been merged, but it's not yet released. You can try it out by pulling the repository and:

```bash
yarn 
yarn build
cd packages/react-static
yarn link

cd path/to/your/project
yarn link react-static
```
