### ISSUE TITLE
`react-static create` displays warning and only works once.

### ISSUE THREAD

**Issue by Herohtar** [react-static/react-static#875]
After running `react-static create` once after a fresh install, it will not work again and fails with a stack trace. Uninstalling and reinstalling will allow you to run it once more, and it again will fail on a second run. It might be worth noting that the first run displays the error message described in https://github.com/nozzle/react-static/issues/874.

### Environment

1.  `react-static -V`: 6.0.2
2.  `node -v`: 11.4.0
3.  `npm -v`: 6.4.1
4.  Operating system: Windows 10 x64
5.  Browser and version (if relevant): N/A

### Steps to Reproduce the problem

**Base your steps off of any freshly installed react-static template!**

1. Run  `npm i -g react-static`
2.  Run `react-static create`
3.  Give the project a name
4. Select `basic`
5. Run `react-static create`
6. See stack trace

### Expected Behavior

`react-static create` can be run more than once

### Actual Behavior

A second run of `react-static create` fails with the following stack trace:

> C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\convert-source-map\index.js:61
>   return SafeBuffer.Buffer.from(json, 'utf8').toString('base64');
>                            ^
> 
> TypeError: Cannot read property 'from' of undefined
>     at Converter.toBase64 (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\convert-source-map\index.js:61:28)
>     at Converter.toComment (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\convert-source-map\index.js:65:21)
>     at generateCode (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\@babel\core\lib\transformation\file\generate.js:78:76)
>     at runSync (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\@babel\core\lib\transformation\index.js:50:51)
>     at transformSync (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\@babel\core\lib\transform.js:43:38)
>     at Object.transform (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\@babel\core\lib\transform.js:22:38)
>     at compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\@babel\register\lib\node.js:73:20)
>     at compileHook (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\@babel\register\lib\node.js:102:12)
>     at Module._compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:77:29)
>     at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Object.newLoader [as .js] (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:88:7)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:659:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.require (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\tunnel-agent/index.js:10:14)
>     at Module._compile (internal/modules/cjs/loader.js:723:30)
>     at Module._compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:83:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Object.newLoader [as .js] (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:88:7)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:659:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.require (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\caw/index.js:5:21)
>     at Module._compile (internal/modules/cjs/loader.js:723:30)
>     at Module._compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:83:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Object.newLoader [as .js] (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:88:7)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:659:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.require (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\download/index.js:5:13)
>     at Module._compile (internal/modules/cjs/loader.js:723:30)
>     at Module._compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:83:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Object.newLoader [as .js] (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:88:7)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:659:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.require (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\download-git-repo/index.js:1:19)
>     at Module._compile (internal/modules/cjs/loader.js:723:30)
>     at Module._compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:83:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Object.newLoader [as .js] (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:88:7)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:659:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (../../src/commands/create.js:9:1)
>     at Module._compile (internal/modules/cjs/loader.js:723:30)
>     at Module._compile (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:83:24)
>     at Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Object.newLoader [as .js] (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\node_modules\pirates\lib\index.js:88:7)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Module.require (internal/modules/cjs/loader.js:659:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at create (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\bin\react-static:94:10)
>     at init (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\bin\react-static:28:12)
>     at Object.<anonymous> (C:\Users\Me\AppData\Roaming\nvm\v11.4.0\node_modules\react-static\bin\react-static:5:1)
>     at Module._compile (internal/modules/cjs/loader.js:723:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
>     at Module.load (internal/modules/cjs/loader.js:620:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
>     at executeUserCode (internal/bootstrap/node.js:342:17)
>     at startExecution (internal/bootstrap/node.js:276:5)
>     at startup (internal/bootstrap/node.js:227:5)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by tannerlinsley** [comment]
Similar to your other issue, I am unable to replicate this. It could be a Windows thing, so if we can find another Windows user to try this out, that would be great.

**Comment by g-ir** [comment]
I'm getting the same error

### Environment
1. `react-static -V`: 6.0.0
2. `node -v`: 10.13.0
3. `npm -v`: 6.4.1
4. Operating system: Windows 10 x64
5. Browser and version (if relevant): N/A

```
C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\convert-source-map\index.js:61
  return SafeBuffer.Buffer.from(json, 'utf8').toString('base64');
                           ^

TypeError: Cannot read property 'from' of undefined
    at Converter.toBase64 (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\convert-source-map\index.js:61:28)
    at Converter.toComment (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\convert-source-map\index.js:65:21)
    at generateCode (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\@babel\core\lib\transformation\file\generate.js:78:76)
    at runSync (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\@babel\core\lib\transformation\index.js:50:51)
    at transformSync (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\@babel\core\lib\transform.js:22:38)
    at compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\@babel\register\lib\node.js:73:20)
    at compileHook (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\@babel\register\lib\node.js:102:12)
    at Module._compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:77:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.require (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\tunnel-agent/index.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.require (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\caw/index.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.require (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\download/index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.require (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\download-git-repo/index.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (../../src/commands/create.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module._compile (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.newLoader [as .js] (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\g-ir\AppData\Local\Yarn\Data\global\node_modules\react-static\bin\react-static-create:6:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

**Comment by tannerlinsley** [comment]
Just released a new version with a refactor of the CLI system and some other windows-specific fixes. Wanna try this again?

**Comment by Herohtar** [comment]
It looks like the error and subsequent crash on second run has been fixed with the recent updates.

I do get some warnings during the dependency installation step, but I don't think they're directly part of `react-static`?
```
Using React Static template: basic
=> Installing dependencies with: Yarn...
warning react-static > babel-preset-react-static > emotion-server > create-emotion-server > html-tokenize > through2 > xtend > object-keys@0.4.0:
warning react-static > eslint-config-react-tools > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```
